// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiXHWD36BHOsM37SnQuwBu3GSyqHtl_lc',
    appId: '1:472678836134:web:b3c853b115b148c2385167',
    messagingSenderId: '472678836134',
    projectId: 'ubisafe-ca262',
    authDomain: 'ubisafe-ca262.firebaseapp.com',
    databaseURL: 'https://ubisafe-ca262-default-rtdb.firebaseio.com',
    storageBucket: 'ubisafe-ca262.firebasestorage.app',
    measurementId: 'G-S33TVNJG13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqvIpgpQSpEea8CDU4_RO8JojI-rFcuz4',
    appId: '1:472678836134:android:6fcea5a51e74c4d8385167',
    messagingSenderId: '472678836134',
    projectId: 'ubisafe-ca262',
    databaseURL: 'https://ubisafe-ca262-default-rtdb.firebaseio.com',
    storageBucket: 'ubisafe-ca262.firebasestorage.app',
  );
}
